services:
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
            - "%locale%"
            - 50


    oc_platform.envoiEmail: 
        class: OC\PlatformBundle\EnvoiEmail\OCEnvoiEmail
        arguments: 
            - "@mailer"

    oc_platform.creationPersistance: 
        class: OC\PlatformBundle\DoctrineListener\CreationListener
        arguments: 
            - "@oc_platform.envoiEmail" 
        tags: 
            - { name: doctrine.event_listener, event: postPersist }       



    oc_platform.advert.purge: 
        class: OC\PlatformBundle\SystemePurge\Purge
        arguments: 
            - '@doctrine.orm.entity_manager'




#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    
