services:
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
            - %locale%
            - 50


    oc_platform.envoiEmail: 
        class: OC\PlatformBundle\EnvoiEmail\OCEnvoiEmail
        arguments: 
            - "@mailer"


#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    
